export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICES_DETAIL = "GET_SERVICES_DETAIL";
export const CLEAN_STATE = "CLEAN_STATE";
export const CLEANER_NAME = "CLEANER_NAME";
export const GET_BY_NAME = "GET_BY_NAME";
